### ISSUE TITLE
How to parse .xlsx content from crul response?

### ISSUE THREAD

**Issue by moldach** [ropensci/crul#161]
I'm trying to figure out how to parse the response since it is an `.xlsx` EXCEL spreadsheet (_and not JSON_)

```
suppressMessages(library(crul))
suppressMessages(library(lubridate))
suppressMessages(library(openxlsx))

# Set ENV variables
to_date <- lubridate::as_date("2021-06-29")
from_date <- lubridate::as_date("2021-06-01")
version = 63973
token = [PRIVATE KEY HERE]

url <- paste0('https://api.targetsafety.info/api/alertcenter/dataset/param?from_date=', from_date, '&to_date=', to_date, '&version=', version, '&token=', token)

(cc <- Async$new(
  url = url
))
(res <- cc$get())
```

Showing `res`: 

```
[[1]]
<crul response> 
  url: https://api.targetsafety.info/api/alertcenter/dataset/param?from_date=2021-06-01&to_date=2021-06-29&version=63973&token=[PRIVATE]
  request_headers: 
  response_headers: 
    status: HTTP/2 200
    date: Tue, 06 Jul 2021 16:06:53 GMT
    content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    content-length: 10815234
    x-powered-by: Express
    access-control-allow-origin: *
    content-disposition: attachment; filename=DATASET-V2-2021-06-01_2021-06-29.xlsx
    etag: W/"a50702-sV45umM0y/Nr9u0V3u0ml8yerK0"
    set-cookie: api_cookie=s%3AgDQh8H24Ajac8HLcr56ns-FHtfdbkTxW.VzXMnwrwHCXiWK4pcT7M1BFauGR9Apy5MW0tRm0qMo0; Path=/; HttpOnly
  params: 
    from_date: 2021-06-01
    to_date: 2021-06-29
    version: 63973
    token: PRIVATE
  status: 200
```

I thought I could try to adapt the [write to disk ](https://docs.ropensci.org/crul/articles/crul.html#write-to-disk)section of the documentation in order to first save the response to a tempfile and then use {`openxlsx`} to read the data; however, this did not work:

```
x <- HttpClient$new(url = url)
f <- tempfile()
res <- x$get(disk = f)
openxlsx::read.xlsx(res$content)
```

> Error: openxlsx can only read .xlsx files
